#! /bin/sh
#
#Copyright (c) 2012-2013 Qualcomm Technologies, Inc.  All Rights Reserved.
#Qualcomm Technologies Proprietary and Confidential.

# QCMAP_Web_CLIENT.   init.d script to start the Data Software's QCMAP_Web_CLIENT. daemon

set -e

case "$1" in
  start)
        echo -n "Starting QCMAP_Web_CLIENT: "
        start-stop-daemon -S -b -a /usr/bin/QCMAP_Web_CLIENT
        echo "done"
        ;;
  stop)
        echo -n "Stopping QCMAP_Web_CLIENT: "
        start-stop-daemon -K -n /usr/bin/QCMAP_Web_CLIENT
        echo "done"
        ;;
  restart)
        $0 stop
        $0 start
        ;;
  *)
        echo "Usage QCMAP_Web_CLIENT { start | stop | restart}" >&2
        exit 1
        ;;
esac

exit 0