#! /bin/sh

set -e

# What value to override the TTL to?
TTLVALUE=64

case "$1" in
start)
    echo -n "Adding TTL override rules: "
    iptables -t mangle -I POSTROUTING -o rmnet+ -j TTL --ttl-set ${TTLVALUE}
    ip6tables -t mangle -I POSTROUTING -o rmnet+ -j HL --hl-set ${TTLVALUE}

    # If your modem is starting in CFUN=0 mode, uncomment this to pass CFUN=1 to it. Hack, but we'll still keep working to figure out what is causing it.
    # echo -e "AT+CFUN=1\r\n" > /dev/smd7

    echo "done"
    ;;
  stop)
    echo -n "Removing TTL override rules: "
    iptables -t mangle -D POSTROUTING -o rmnet+ -j TTL --ttl-set ${TTLVALUE} &>/dev/null || true
    ip6tables -t mangle -D POSTROUTING -o rmnet+ -j HL --hl-set ${TTLVALUE} &>/dev/null || true
    echo "done"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage ttl-override { start | stop | restart }" >&2
    exit 1
    ;;
esac

exit 0
