#! /bin/sh

set -e

# What value to override the TTL to?
TTLVALUE=65

case "$1" in
start)
    echo -n "Adding TTL override rules: "
    iptables -t mangle -I POSTROUTING -o rmnet+ -j TTL --ttl-set ${TTLVALUE}
    ip6tables -t mangle -I POSTROUTING -o rmnet+ -j HL --hl-set ${TTLVALUE}
    echo "done"
    ;;
  stop)
    echo -n "Removing TTL override rules: "
    iptables -t mangle -D POSTROUTING -o rmnet+ -j TTL --ttl-set ${TTLVALUE} &>/dev/null || true
    ip6tables -t mangle -D POSTROUTING -o rmnet+ -j HL --hl-set ${TTLVALUE} &>/dev/null || true
    echo "done"
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage ttl-override { start | stop | restart }" >&2
    exit 1
    ;;
esac

exit 0
